on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'      
    - name: Build project
      run: |
        npm install
        npm run build
    - name: Upload site to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.proyectobios.com
        username: pybiot
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/
        server-dir: public_html/
